module.exports = {
  rootNotionPageId: '9b036ea279d04498ba907620e641c475',
  rootNotionSpaceId: null,
  name: 'hjinn',
  domain: 'hjinn.it',
  author: 'Hojun In',
  description: 'Example site description',
  socialImageTitle: 'Transitive Bullshit',
  socialImageSubtitle: 'Hello World! 👋',
  twitter: 'hjinn',
  github: 'hojunin',
  linkedin: 'hjinn',
  defaultPageIcon: null,
  defaultPageCover: null,
  defaultPageCoverPosition: 0.5,
  imageCDNHost: null,
  utterancesGitHubRepo: null,
  isPreviewImageSupportEnabled: false,
  pageUrlOverrides: null
}
